apiVersion: apps/v1
kind: Deployment
metadata:
  name: questbook-deployment
  labels:
    app: questbook
  namespace: unbiased
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questbook
  template:
    metadata:
      labels:
        app: questbook
    spec:
      containers:
      - name: questbook
        image: ibmcom/guestbook
        ports:
        - containerPort: 80
